repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
  - id: name-tests-test
  - id: requirements-txt-fixer
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v2.5.0
  hooks:
  - id: setup-cfg-fmt
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format
- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.1.0
  hooks:
  - id: add-trailing-comma
- repo: https://github.com/asottile/pyupgrade
  rev: v3.17.0
  hooks:
  - id: pyupgrade
    args: [--py38-plus]
- repo: https://github.com/google/yamlfmt
  rev: v0.13.0
  hooks:
  - id: yamlfmt
    args: ["-formatter", "indent=2,indentless_arrays=true,trim_trailing_whitespace=true,eof_newline=true,retain_line_breaks_single=true"]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.2
  hooks:
  - id: mypy
